"""Initial revision

Revision ID: 5a03bb229eb8
Revises: 
Create Date: 2025-04-14 09:02:09.461452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a03bb229eb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobby',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hobby')),
    schema='public'
    )
    op.create_index(op.f('ix_public_hobby_title'), 'hobby', ['title'], unique=True, schema='public')
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_male', sa.Boolean(), nullable=True, comment='Пол пользователя (True - мужской, False - женский)'),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_username'), 'user', ['username'], unique=True, schema='public')
    op.create_table('userhobby',
    sa.Column('user', sa.Uuid(), nullable=False),
    sa.Column('hobby', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hobby'], ['public.hobby.id'], name=op.f('fk_userhobby_hobby_hobby')),
    sa.ForeignKeyConstraint(['user'], ['public.user.id'], name=op.f('fk_userhobby_user_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userhobby')),
    sa.UniqueConstraint('user', 'hobby', name='uq_user_hobby'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userhobby', schema='public')
    op.drop_index(op.f('ix_public_user_username'), table_name='user', schema='public')
    op.drop_table('user', schema='public')
    op.drop_index(op.f('ix_public_hobby_title'), table_name='hobby', schema='public')
    op.drop_table('hobby', schema='public')
    # ### end Alembic commands ###
