"""Add photo_url field to users

Revision ID: cea7ebb03f05
Revises: 26bcc4f81f1c
Create Date: 2026-01-15 17:31:22.030088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea7ebb03f05'
down_revision: Union[str, Sequence[str], None] = '26bcc4f81f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_url', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo_url')
    # ### end Alembic commands ###
